### ISSUE TITLE
The project doesn't compile in sbt

### ISSUE THREAD

**Issue by hnrklssn** [nmarshall23/desktop-pushbullet#1]
When running sbt compile I get the following error message: [error](*:update) sbt.ResolveException: unresolved dependency: com.github.taksan#native-tray-adapter;1.2-SNAPSHOT: not found.

I was planning on running the program to get a clearer view of the code flow since I am working on an akka actor project where I too want to use the pushbullet api. Do you happen to have an idea of how I can get this project to compile? While we're on the subject, I can't find any license for the code. Would you mind if I include PushbulletAPI.scala in my own project?

**Comment by hnrklssn** [comment]
Never mind, downloaded the release version and it compiles correctly. Also found the license, must have been a bit sleepy when looking last night since it was right there in the root folder. :)

**Comment by nmarshall23** [comment]
no problem dude. If you have any questions let me know. This code is rather old I have no idea if it still works.
